chore: update building script

diff --git a/.github/workflows/build-daily.yml b/.github/workflows/build-daily.yml
--- a/.github/workflows/build-daily.yml
+++ b/.github/workflows/build-daily.yml
@@ -98,14 +98,20 @@ jobs:
         dir: ${{ github.workspace }}
         modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
     - name: Build for macOS
+      # 278ERROR: no file at "/usr/local/opt/libiodbc/lib/libiodbc.2.dylib" 
+      # brew unlink unixodbc
+      # brew install libiodbc
+      # ERROR: no file at "/Applications/Postgres.app/Contents/Versions/14/lib/libpq.5.dylib"
       run: |
-        brew install postgresql
-        psql --version
+        echo "[fix]ERROR: no file at "/usr/local/opt/libiodbc/lib/libiodbc.2.dylib"
         brew unlink unixodbc
         brew install libiodbc
-        ls /Applications
         mkdir build
         cd build
+        ls /Applications || true
+        ls /Applications/Postgres.app || true
+        ls /Applications/Postgres.app/Contents || true
+        ls /Applications/Postgres.app/Contents/Versions || true
         cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/6.5.3/clang_64/lib/cmake/Qt6' -DCMAKE_BUILD_TYPE:STRING=Release -G "Unix Makefiles" ../
         cmake --build . --target QtSwissArmyKnife
         dir && dir ./sak && dir ./sak/QtSwissArmyKnife
